version: "3.7"

services:
  pubsub-emulator:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:367.0.0-emulators
    command:
      [
        "gcloud",
        "beta",
        "emulators",
        "pubsub",
        "start",
        "--host-port=0.0.0.0:8085",
        "--project=bike4life-project",
      ]
    ports:
      - "8085:8085"

  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    ports:
      - "80:80"
    restart: "unless-stopped"

  auth-api:
    build:
      context: .
      dockerfile: ./apps/auth-api/Dockerfile
    ports:
      - "8081:8081"
    restart: "unless-stopped"
    links:
      - pubsub-emulator
    depends_on:
      - pubsub-emulator
    env_file: .env.production

  routes-api:
    build:
      context: .
      dockerfile: ./apps/routes-api/Dockerfile
    ports:
      - "8080:8080"
    restart: "unless-stopped"
    links:
      - pubsub-emulator
    depends_on:
      - pubsub-emulator
    env_file: .env.production

  notifier:
    build:
      context: .
      dockerfile: ./apps/notifier/Dockerfile
    ports:
      - "8082:8082"
    restart: "unless-stopped"
    links:
      - pubsub-emulator
    depends_on:
      - pubsub-emulator
    env_file: .env.production

  route-checker:
    build:
      context: .
      dockerfile: ./apps/route-checker/Dockerfile
    ports:
      - "3004:3333"
    restart: "unless-stopped"
    links:
      - pubsub-emulator
    depends_on:
      - pubsub-emulator
    env_file: .env.production

  frontend:
    build:
      context: ./bike4life-frontend
      dockerfile: ./Dockerfile
    ports:
      - "8088:80"
    restart: "unless-stopped"
    env_file: .env.production
