version: '3.7'

services:
  pubsub-emulator:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:367.0.0-emulators
    command:
      [
        "gcloud",
        "beta",
        "emulators",
        "pubsub",
        "start",
        "--host-port=0.0.0.0:8085",
        "--project=dev-pubsub-project"
      ]
    ports:
      - "8085:8085"

  notifier:
    build:
      context: ./notifier/
      target: development-build-stage
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./notifier:/app
      - ./notifier/node_modules:/app/node_modules
    restart: 'unless-stopped'
    links:
      - mongo
    depends_on:
      - mongo
    env_file: .env

  auth-api:
    build:
      context: ./auth-api/
      target: development-build-stage
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    volumes:
      - ./auth-api:/app
      - ./auth-api/node_modules:/app/node_modules
    restart: 'unless-stopped'
    links:
      - mongo
    depends_on:
      - mongo
    env_file: .env

  mongo:
    image: mvertes/alpine-mongo
    ports:
      - '27017:27017'
