version: "3.7"

services:
  auth-api:
    build:
      context: .
      dockerfile: ./apps/auth-api/Dockerfile
    ports:
      - "3001:3333"
    restart: "unless-stopped"
    links:
      - mongo
      - pubsub-emulator
    depends_on:
      - mongo
      - pubsub-emulator
    env_file: .env.production

  routes-api:
    build:
      context: .
      dockerfile: ./apps/routes-api/Dockerfile
    ports:
      - "3002:3333"
    restart: "unless-stopped"
    links:
      - mongo
      - pubsub-emulator
    depends_on:
      - mongo
      - pubsub-emulator
    env_file: .env.production

  notifier:
    build:
      context: .
      dockerfile: ./apps/notifier/Dockerfile
    ports:
      - "3003:3333"
    restart: "unless-stopped"
    links:
      - mongo
      - pubsub-emulator
    depends_on:
      - mongo
      - pubsub-emulator
    env_file: .env.production

  route-checker:
    build:
      context: .
      dockerfile: ./apps/route-checker/Dockerfile
    ports:
      - "3004:3333"
    restart: "unless-stopped"
    links:
      - mongo
      - pubsub-emulator
    depends_on:
      - mongo
      - pubsub-emulator
    env_file: .env.production
