const {
    MONGO_DB_HOST,
    MONGO_DB_PORT,
    MONGO_DB_USER,
    MONGO_DB_PASSWORD,
    ROUTE_CHECKER_DATABASE_NAME,
    PUBSUB_PROJECT_ID,
    ROUTE_CHECKER_PUBSUB_SUBSCRIPTION_NAME,
    ROUTE_CHECKER_PUBSUB_TOPIC_NAME,
    OPEN_TRIP_MAP_URL,
    ROUTE_CHECKER_API_KEY,
    ROUTE_CHECKER_PORT,
    ROUTE_CHECKER_DATABASE_URL
} = process.env


export const mongoConnectionSettings = {
    url: ROUTE_CHECKER_DATABASE_URL ? ROUTE_CHECKER_DATABASE_URL : `mongodb://${MONGO_DB_USER}:${MONGO_DB_PASSWORD}@${MONGO_DB_HOST}:${MONGO_DB_PORT}/${ROUTE_CHECKER_DATABASE_NAME}?authSource=admin`,
}

export const pubSubSettings = {
    projectId: PUBSUB_PROJECT_ID,
    subscriptionName: ROUTE_CHECKER_PUBSUB_SUBSCRIPTION_NAME,
    topicName: ROUTE_CHECKER_PUBSUB_TOPIC_NAME
}

export const mapSettings = {
    url: OPEN_TRIP_MAP_URL,
    key: ROUTE_CHECKER_API_KEY,
}

export const apiSettings = {
    port: ROUTE_CHECKER_PORT
}
