openapi: 3.0.0
info:
  title: Notifier API
  description: This API is in charge of sending notifications using SendGrid API.
  version: 1.0.0
servers:
  - url: http://localhost:8085/v1/

paths:
  /dev-pubsub-project/topics/notifier-topic:publish:
    post:
     requestBody:
        description: 
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/messages"
      responses:
        "200":
          description: Return a 200 status to indicate that the data was received successfully


components:
  schemas:
    messages:
      required:
        - data
        - attributes
      properties:
        data:
          type: string
        attributes:
          type: 
            $ref: "#/components/schemas/topic"
    topic:
      type: object
      properties: 
        type: string

