openapi: 3.0.3
info:
  title: Routes Api
  description: This API is responsible for routes management. Get routes, delete/edit routes, create routes...
  version: 1.0.0
servers:
  - url: https://localhost:3333
tags:
  - name: routes
    description: This endpoint manage all the information related to routes

paths:
  /routes:
    post:
      tags:
        - routes
      summary: Creates new route
      parameters:
      - $ref: "#/components/parameters/token"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/route'
        required: true
      responses:
        '201':
          description: Route created successfully
        '400':
            $ref: "#/components/responses/BadRequest"
        '404':
            $ref: "#/components/responses/NotFound"

  /routes/{routeId}:
    get:
      tags:
        - routes
      summary: Find route by ID
      parameters:
        - name: routeId
          in: path
          description: ID of route to return
          required: true
          schema:
            type: string
            
      responses:
        '200':
          description: Route information obtained successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/route'          
        '400':
            $ref: "#/components/responses/BadRequest"
        '404':
            $ref: "#/components/responses/NotFound"

    put:
      tags:
        - routes
      summary: Update an existing route
      parameters:
        - $ref: "#/components/parameters/token"
        - name: routeId
          in: path
          description: ID of route to return
          required: true
          schema:
            type: string     
      requestBody:
        description: Update an existent route in the DB
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/route'
        required: true
      responses:
        '200':
          description: Route updated succesfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/route'          
        '400':
            $ref: "#/components/responses/BadRequest"
        '404':
            $ref: "#/components/responses/NotFound"

    delete:
      tags:
        - routes
      summary: Deletes a route
      parameters:
        - $ref: "#/components/parameters/token"
        - name: routeId
          in: path
          description: Route id to delete
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Route deleted successfully
        '400':
            $ref: "#/components/responses/BadRequest"
        '404':
            $ref: "#/components/responses/NotFound"

components:

  responses:
    BadRequest:
      description: (BadRequest) the data sent is incorrect or some required data is missing
    NotFound:
      description: (NotFound) no information found
    
  parameters:
    token:
      name: token
      in: header
      description: Authentication Token
      required: true
      schema:
        type: string
      
  schemas:
    route:
      type: object
      properties:
        coordinates:
          type: array
          items:
            type: number
            items:
              type: string
        date:
          type: string
        name:
          type: string
        description:
          type: string
        estimatedDuration:
          type: number
        userId:
          type: string
