openapi: 3.0.3
info:
  title: Routes Api
  description: This API is responsible for routes management. Get routes, delete/edit routes, create routes...
  version: 1.0.0
servers:
  - url: http://localhost:3333
tags:
  - name: routes
    description: This endpoint manage all the information related to routes

paths:
  /routes:
    post:
      tags:
        - routes
      summary: Creates new route
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/route'
        required: true
        
      responses:
        '201':
          description: Route created successfully
        '400':
            $ref: "#/components/responses/ValidationFailed"
        '401':
            $ref: "#/components/responses/Unauthorized"
        '409':
          $ref: "#/components/responses/DuplicateKeyError"

    get:
      tags:
        - routes
      summary: List of routes
      security:
        - bearerAuth: []
            
      responses:
        '200':
          description: List of routes obtained successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/route'      
        '401':
            $ref: "#/components/responses/Unauthorized"
          
  /routes/{routeId}:
    get:
      tags:
        - routes
      summary: Find route by ID
      security:
        - bearerAuth: []
      parameters:
        - name: routeId
          in: path
          description: ID of route to return
          required: true
          schema:
            type: string
            
      responses:
        '200':
          description: Route information obtained successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/route'          
        '400':
            $ref: "#/components/responses/ValidationFailed"
        '401':
            $ref: "#/components/responses/Unauthorized"
        '403':
            $ref: "#/components/responses/Forbiden"
        '404':
            $ref: "#/components/responses/NotFound"

    put:
      tags:
        - routes
      summary: Update an existing route
      security:
        - bearerAuth: []
      parameters:
        - name: routeId
          in: path
          description: ID of route to return
          required: true
          schema:
            type: string     
            
      requestBody:
        description: Update an existent route in the DB
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/route'
        required: true
        
      responses:
        '200':
          description: Route updated succesfully
        '400':
            $ref: "#/components/responses/ValidationFailed"
        '401':
            $ref: "#/components/responses/Unauthorized"
        '403':
            $ref: "#/components/responses/Forbiden"
        '404':
            $ref: "#/components/responses/NotFound"

    delete:
      tags:
        - routes
      summary: Deletes a route
      security:
        - bearerAuth: []
      parameters:
        - name: routeId
          in: path
          description: Route id to delete
          required: true
          schema:
            type: string
            
      responses:
        '204':
          description: Route deleted successfully
        '400':
            $ref: "#/components/responses/ValidationFailed"
        '401':
            $ref: "#/components/responses/Unauthorized"
        '403':
            $ref: "#/components/responses/Forbiden"
        '404':
            $ref: "#/components/responses/NotFound"


components:

  responses:
    ValidationFailed:
      description: Validation Failed
    Unauthorized:
      description: Unauthorized
    Forbiden:
      description: You are not allowed to access this resource
    NotFound:
      description: Not found
    DuplicateKeyError:
      description: Duplicate key error
    
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      
  schemas:
    route:
      type: object
      properties:
        coordinates:
          type: array
          items:
            type: array
            items:
              type: number
        date:
          type: string
          format: date-time
        name:
          type: string
        description:
          type: string
        estimatedDuration:
          type: number
        userId:
          type: string
        _id:
          type: string
      required:
        - coordinates
        - date
        - name
        - description
        - estimatedDuration
        