const {
  PUBSUB_PROJECT_ID,
  NOTIFIER_PUBSUB_SUBSCRIPTION_NAME,
  NOTIFIER_PUBSUB_TOPIC_NAME,
  TO_REPLY_TO_EMAIL_SENDGRID,
  SENDGRID_APY_KEY,
} = process.env;

export const sendgridSettings = {
  PUBSUB_PROJECT_ID,
  NOTIFIER_PUBSUB_SUBSCRIPTION_NAME,
  NOTIFIER_PUBSUB_TOPIC_NAME,
  TO_REPLY_TO_EMAIL_SENDGRID,
  SENDGRID_APY_KEY,
};
